
package server.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Tue Feb 11 09:21:24 CET 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "getVoyagesResponse", namespace = "http://webservice.server/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getVoyagesResponse", namespace = "http://webservice.server/")

public class GetVoyagesResponse {

    @XmlElement(name = "return")
    private java.util.ArrayList<server.data.Voyage> _return;

    public java.util.ArrayList<server.data.Voyage> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.ArrayList<server.data.Voyage> new_return)  {
        this._return = new_return;
    }

}

