
package server.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Tue Feb 11 09:21:24 CET 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "getVoyages", namespace = "http://webservice.server/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getVoyages", namespace = "http://webservice.server/")

public class GetVoyages {


}

