package client.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-11T09:24:27.316+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "CatalogueService", 
                  wsdlLocation = "http://localhost:8080/AgenceDeVoyage/services/CataloguePort?wsdl",
                  targetNamespace = "http://webservice.server/") 
public class CatalogueService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.server/", "CatalogueService");
    public final static QName CataloguePort = new QName("http://webservice.server/", "CataloguePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/AgenceDeVoyage/services/CataloguePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CatalogueService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/AgenceDeVoyage/services/CataloguePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CatalogueService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CatalogueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogueService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatalogueService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatalogueService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatalogueService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Catalogue
     */
    @WebEndpoint(name = "CataloguePort")
    public Catalogue getCataloguePort() {
        return super.getPort(CataloguePort, Catalogue.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Catalogue
     */
    @WebEndpoint(name = "CataloguePort")
    public Catalogue getCataloguePort(WebServiceFeature... features) {
        return super.getPort(CataloguePort, Catalogue.class, features);
    }

}
