package client.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-11T09:24:27.308+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://webservice.server/", name = "Catalogue")
@XmlSeeAlso({ObjectFactory.class})
public interface Catalogue {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVoyages", targetNamespace = "http://webservice.server/", className = "client.webservice.GetVoyages")
    @WebMethod
    @ResponseWrapper(localName = "getVoyagesResponse", targetNamespace = "http://webservice.server/", className = "client.webservice.GetVoyagesResponse")
    public java.util.List<client.webservice.Voyage> getVoyages();
}
