
package client.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-11T09:24:27.245+01:00
 * Generated source version: 2.7.8
 * 
 */
public final class Catalogue_CataloguePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.server/", "CatalogueService");

    private Catalogue_CataloguePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CatalogueService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CatalogueService ss = new CatalogueService(wsdlURL, SERVICE_NAME);
        Catalogue port = ss.getCataloguePort();  
        
        {
        System.out.println("Invoking getVoyages...");
        java.util.List<client.webservice.Voyage> _getVoyages__return = port.getVoyages();
        System.out.println("getVoyages.result=" + _getVoyages__return);


        }

        System.exit(0);
    }

}
